### ISSUE TITLE
"BasicBlock requested for unrecognized address" error when running "wp-now"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/playground-tools#122]
I've been using "wp-now" successfully until a few weeks where I started getting this error everytime I try to use `wp-now`

```
⬢  custom-block-color-settings  master ⦾ npx @wp-now/wp-now start        
Starting the server......
directory: /Users/juanmanuelgarrido/PROJECTS/2023/WORDPRESS/GUTENBERG/custom-block-color-settings
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
 %                                                                                                                                   
⬢  custom-block-color-settings  master ⦾ npx @wp-now/wp-now start --reset
Starting the server......
directory: /Users/juanmanuelgarrido/PROJECTS/2023/WORDPRESS/GUTENBERG/custom-block-color-settings
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
Created a fresh SQLite database and wp-content directory.
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
 %                              
```

**Comment by danielbachhuber** [comment]
Huh! That's an interesting error.

Does it happen when you run `npx @wp-now/wp-now start` in other directories too? Any ideas what `BuilderBase` or `BasicBlock` might be?

**Comment by juanmaguitar** [comment]
> Does it happen when you run npx @wp-now/wp-now start in other directories too? 

Yes, I'm getting this error every time I run `wp-now` on any folder

>Any ideas what BuilderBase or BasicBlock might be?

No idea, but a [quick search in Google](https://www.google.com/search?q=assertion+failed+%5Bblock+%21%3D+nullptr%5D&sca_esv=578400713&ei=kOxBZdnwHKGchbIPlImToA0&ved=0ahUKEwjZ-L3fkqKCAxUhTkEAHZTEBNQQ4dUDCBE&uact=5&oq=assertion+failed+%5Bblock+%21%3D+nullptr%5D&gs_lp=Egxnd3Mtd2l6LXNlcnAiI2Fzc2VydGlvbiBmYWlsZWQgW2Jsb2NrICE9IG51bGxwdHJdMgUQIRigATIFECEYoAFIzgVQywNYywNwAXgBkAEAmAFqoAFqqgEDMC4xuAEDyAEA-AEC-AEBwgIKEAAYRxjWBBiwA-IDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp) shows that is an error happening across different products on Mac OS (with M* processors I would say as per [this](https://github.com/PowerShell/PowerShell/issues/17655#issuecomment-1180893453), [this](https://github.com/ethereum/solidity/issues/13523#issuecomment-1284130107) and [this](https://github.com/prisma/prisma/issues/17869)). 
- https://github.com/ethereum/solidity/issues/13523
- https://github.com/PowerShell/PowerShell/issues/17655

**Comment by juanmaguitar** [comment]
I solved it! ✌️
It's an issue with macOS with M*processors and the "architecture" used from the terminal.
The key to the solution is in [this issue](https://github.com/prisma/prisma/issues/17869) and more specifically in [this comment](https://github.com/prisma/prisma/issues/17869#issuecomment-1687734564)

> Just for people looking for a solution:
> if you are using iterm, you might running it with rosetta, and it can create issues. After searching I come up with this:
> 
> go to Applications
> duplicate "iTerm.app"
> Right Click > Get Info
> Make sure "open with rosetta" is unchecked
> Open this iterm
> $ arch should output arm64
> $ node -e 'console.log(process.arch) should output arm64
> If not, reinstall node (nvm un/install)
> Should be better now

After following these steps `wp-now` works again normally

```
⬢  custom-block-color-settings  master ⦾ npx @wp-now/wp-now start --reset
Starting the server......
directory: /Users/juanmanuelgarrido/PROJECTS/2023/WORDPRESS/GUTENBERG/custom-block-color-settings
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
Created a fresh SQLite database and wp-content directory.
Server running at http://localhost:8881
```

**Comment by danielbachhuber** [comment]
@juanmaguitar Nice find! Thanks for reporting back with your fix 😊
