### ISSUE TITLE
GitHub action to release wp-now

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#127]
Releasing wp-now requires a local development setup. It would be convenient to have a GitHub action one can just run – similarly to the one present in https://github.com/WordPress/wordpress-playground.

Done is:

* There's a GitHub action to release a new version of `wp-now` packages on npm

**Comment by danielbachhuber** [comment]
+100 on my end.

I also don't have a lot of confidence in the release mechanism, as I often have to run it twice to get the release created.

**Comment by sejas** [comment]
It was solved on https://github.com/WordPress/playground-tools/pull/190
