### ISSUE TITLE
Github Action to deploy the WordPress Playground block plugin

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#149]
It would be nice to release a new version of the plugin with a click of a button.

See https://joost.blog/github-actions-wordpress/

cc @jdevalk

**Comment by jdevalk** [comment]
Might be harder with the plugin not in its own repo, probably a bit more config work.

**Comment by adamziel** [comment]
Another resource: https://github.com/10up/action-wordpress-plugin-deploy

FYI we have this issue @bgrgicak

**Comment by adamziel** [comment]
We have that workflow now: https://github.com/WordPress/playground-tools/blob/trunk/.github/workflows/release-playground-block.yml
