### ISSUE TITLE
Playground Plugin: Should previewing a plugin in wp-admin use that plugin's Blueprint?

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#155]
The Playground plugin adds a "Preview on a copy of my site" button to every plugin in wp-admin:

<img src="https://github.com/WordPress/playground-tools/assets/205419/0f410141-8b90-46cf-b85c-2e1aba2dc97d" width="400"/>

That button clones the entire website in Playground and then installs the plugin on top of that.

Some plugins provide a custom Blueprint meant to set up a useful preview when "Live preview" is clicked in the WordPress plugin directory:

<img src="https://github.com/WordPress/playground-tools/assets/205419/40093066-03fa-46d9-9697-1ceb0718a3a9" width="500"/>

### Should that Blueprint is used in wp-admin? My gut says _no_

The plugin directory Blueprints are written with a vanilla WordPress site in mind. They'll typically create dummy content, change site options, and so on to reach a minimal preview environment. In some cases, like bbpress, that makes a lot of sense even in the context of your site as it doesn't have any forums in place. In other cases, that would only add confusing bloat like lorem ipsum pages when your site already has pages.

Then, applying a Blueprint means the preview experience will be very different from the Installing experience. At best, you won't get the setup wizard. At worst, you'll think "what the... is this plugin going to create 50 dummy posts when I install it? I better go for another one".

### /wp-admin preview may not require a Blueprint, but a nice `plugin_activate` handler

I'm not sure how a Blueprint could set up a neat and sensible preview on any WordPress site, regardless of what contents, theme, and options it has. Maybe it shouldn't? In which case there would only be two options:

* Preview on my site – the same as "install", only opened in Playground
* Preview on a demo site – applies the Blueprint to a vanilla WordPress installation

For a better "on my site" experience, the plugin would have to set itself up on installation which could be a good thing regardless of Playground.

@bgrgicak  @tellyworth  @StevenDufresne @jdevalk

**Comment by jdevalk** [comment]
If plugins do custom things in their blueprint, they should just consider this use case. I would favor running those custom blueprints in all instances and have only one "plugin Blueprint experience".  We could consider setting an extra constant for those plugins to tie into that.

I'm not entirely sure what you mean with "/wp-admin preview" to be honest; or with "preview on my site"? Would that install the plugin on a playground copy of your site? Or what are you thinking about?

**Comment by adamziel** [comment]
> Would that install the plugin on a playground copy of your site? Or what are you thinking about?

That's exactly the point! I just adjusted the description to make that clearer. 

> I would favor running those custom blueprints in all instances and have only one "plugin Blueprint experience".

If we're talking about vanilla WordPress sites, I 100% agree.

If we're talking about previewing on a copy of your site, I think I'd be very confused if a Blueprint imported 50 posts and changed the site title. I'm also hesitant about introducing conditional statements into Blueprints are they'd quickly become a new programming language.

**Comment by StevenDufresne** [comment]
The title of this issue somewhat implies that a blueprint should be used. 

If I'm testing a plugin on my site, I want it to function **exactly** how it would if I were to install the plugin on my site. The blueprint plays no part in that install.

**Comment by bgrgicak** [comment]
Just to add to what Steven and Adam already mentioned.

I don't think that previews on a site should use blueprints. If there are extra steps the developer wants to do on every installation they should be part of the plugin, not a blueprint. This way all users benefit when installing the product. 

Blueprints are meant for vanilla site previews and give you a quick overview of the features. They are a great way for plugin owners to set up a new site on the fly.

Plugin previews in the context of your site, don't need a quick overview, they need to be a safe way to test a plugin on your site without breaking it. As I see it you need to test the compatibility between different plugins and confirm if the advertised functionality works in the way you need it to work.

**Comment by adamziel** [comment]
Let’s move forward with _not_ using Blueprints in context of „preview on my site”, then.
