### ISSUE TITLE
VS Code: Could not mount error 

### ISSUE THREAD

**Issue by bph** [WordPress/playground-tools#160]
/Users/pauli/.wp-now/sqlite-database-integration-main/db.copy: There is no such file or directory OR the parent directory does not exist.

or what is it that I am doing wrong? 
![Screenshot 2024-02-19 at 19 10 34](https://github.com/WordPress/playground-tools/assets/39980/333f3110-e8a5-4048-8eae-111036ba9c8d)

**Comment by adamziel** [comment]
The VS Code plugin could use an update since there were important improvements in how the sqlite-database-integration plugin and wp-now work.

**Comment by adamziel** [comment]
@bph this should be fixed in the latest version of the VS Code extension. Feel free to reopen if the problem persists.

**Comment by bph** [comment]
Just to clarify: the latest version: was there one released after I filed this issue?

**Comment by adamziel** [comment]
@bph yes, just today!

**Comment by bph** [comment]
Thanks, @adamziel for clarifying. 
Yes, it's now loading/mounting. 
Yay! 🥳

The release notes mention a 0.0.17 version, which is not in the list of available versions. 
![Screenshot 2024-03-14 at 10 09 43](https://github.com/WordPress/playground-tools/assets/39980/b67e3c62-5113-4350-a86b-14bf6edb2c2f)
![Screenshot 2024-03-14 at 10 07 47](https://github.com/WordPress/playground-tools/assets/39980/eeeccd2a-37e0-4f23-92ba-dba704c02882)
---
It mentioned that it loads the latest WordPress version, but in fact only loaded with WordPress 6.4.2. The latest version is 6.4.3 
![Screenshot 2024-03-14 at 10 01 26](https://github.com/WordPress/playground-tools/assets/39980/1aca8261-43f8-4992-b3f5-d4c8e49820b3)

![Screenshot 2024-03-14 at 10 00 07](https://github.com/WordPress/playground-tools/assets/39980/c076d6bc-6f2c-49d5-914c-ef1b7c67f249)

**Comment by adamziel** [comment]
@bph Yay! 🎉  The WordPress versions issue is tracked separately here: https://github.com/WordPress/playground-tools/issues/187
