### ISSUE TITLE
Playground block: Not showing up on a fresh WordPress install

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#170]
@bbertucc reported:

> I tried to download the plugin and install it on a fresh install with no luck - it never came up when looking for blocks.

One hypothesis I have is that the block is hard to find in the inserter because the plugin doesn't provide any search keyword. But perhaps there's a critical bug. Let's double check that.

**Comment by bbertucc** [comment]
That may be the reason. I tried searching but didn't see it. Didn't really look too hard elsewhere

**Comment by adamziel** [comment]
The discussion in the other thread suggests the block shows up after all. I've added a few more search keywords to make sure it's easier to find.
