### ISSUE TITLE
VSCode extension could not mount

### ISSUE THREAD

**Issue by bph** [WordPress/playground-tools#189]
After a new full install of the VS Code extension, seems to be version 0.1.55 I get an error message: 

`WordPress Playground error: Could not mount /Users/pauli/.wp-now/sqlite-database-integration-main/db.copy: There is no such file or directory OR the parent directory does not exist.`

 I haven't been able to us the VS Code Extension for months now, together with 5,390 other users who downloaded the extension. If there is no ongoing maintenance available, I would suggest to remove it from the Extension marketplace.

**Comment by adamziel** [comment]
@bph I just released a new version of the extension (1.6.0) – would you confirm it solves the problem for you? I'll close this for now, but let's reopen if the problem persists.

> I haven't been able to us the VS Code Extension for months now, together with 5,390 other users who downloaded the extension.

The issue affected folks who tried to update the SQLite plugin. I agree the timeline for this fix was far from perfect. Fortunately there's more people maintaining Playground now and we're also working on error monitoring so it will be much easier to detect problems and prioritize fixes going forward. Thank you for coming back to report the issue @bph  🙌
