### ISSUE TITLE
incorrect \n parsing. And missing adminbar/not loggedin

### ISSUE THREAD

**Issue by janw-me** [WordPress/playground-tools#193]
![Screenshot from 2024-03-17 09-24-51](https://github.com/WordPress/playground-tools/assets/1026882/b60bca64-cb50-4bf7-82fa-23bf61d9190b)

Viewed together with @adamziel yesterday at Cloudfest.

**Comment by adamziel** [comment]
Ccing @bgrgicak

**Comment by bgrgicak** [comment]
@janw-me would you be able to share more details about this issue?
I'm unable to recreate it.

**Comment by adamziel** [comment]
@bgrgicak we just clicked the "Sandbox site" on Janw's local blog after installing the Playground plugin from GitHub releases. I wonder if something is off with stringifying data to INSERT queries – perhaps newline code points sometimes come across as two characters `\` and `n` ?

**Comment by bgrgicak** [comment]
Thanks! This already helps.

**Comment by bgrgicak** [comment]
I can recreate the incorrect `\n` parsing, but not the adminbar.

@janw-me are there any errors in the browser console when Playground is loaded? The missing adminbar makes me think that there is an error in the blueprint that prevents it from executing all steps (login is the last step).

**Comment by adamziel** [comment]
@bgrgicak could it be that a custom admin username or password would break the autologin process?

**Comment by bgrgicak** [comment]
> @bgrgicak could it be that a custom admin username or password would break the autologin process?

Good catch! A custom password breaks login.

I can fix both issues.

**Comment by bgrgicak** [comment]
@adamziel I see two solutions for the login issue.

The first solution would be to add a user and password to Playground and use these credentials to login. It's simple to implement, but it modifies the DB data and could be hard to remove if we ever want to allow Playground to site syncing.

Alternatively, we could programmatically login the user. I explored this but wasn't able to get it to work. I assume there are some issues with the way I'm setting cookies.

Custom cookie example in `packages/playground/assets/js/playground.js`
```
	const response = await client.run({
		code: `<?php require_once '/wordpress/wp-load.php';
			echo json_encode(array(
				'value' => wp_generate_auth_cookie( ${playground.userId}, time() + ( 12 * HOUR_IN_SECONDS ) ),
				'name' => AUTH_COOKIE
			));`,
	});
	if (response.json) {
		document.cookie = `${response.json.name}=${response.json.value}`;
	}
```

Using WordPress functions  example in `packages/playground/assets/js/playground.js`
```
	const response = await client.run({
		code: `<?php require_once '/wordpress/wp-load.php';
			$user = get_user_by( 'id', ${playground.userId} );
			if( $user ) {
				wp_clear_auth_cookie();
				wp_set_current_user( $user->ID );
				wp_set_auth_cookie( $user->ID, true, false );
				do_action( 'wp_login', $user->user_login );
			}`,
	});
```

**Comment by adamziel** [comment]
@bgrgicak `client.run()` doesn't go through the request handler where the cookies are stored. It could work as an `mu-plugin`, though

**Comment by bgrgicak** [comment]
I tried adding the mu-plugin using a blueprint, but it didn't work.

When I add the code to the 0-playground.php mu-plugin, login works.

```
	{
				step: 'writeFile',
				path: '/wordpress/wp-content/mu-plugins/0-login.php',
				data: `<?php
					add_action( 'init', function() {
						if ( is_user_logged_in() ) {
							return;
						}
						$user = get_user_by( 'id', ${playground.userId} );
						if( $user ) {
							wp_set_current_user( $user->ID, $user->user_login );
							wp_set_auth_cookie( $user->ID );
							do_action( 'wp_login', $user->user_login, $user );
						}
					} );
				`,
			},
```

**Comment by adamziel** [comment]
@bgrgicak maybe some `error_log()` statements would be helpful 😄

**Comment by janw-me** [comment]
Looks like I'm late to the party. But just in case it helps, there are errors.
As said it's a local(by flywheel) site with user `admin` with pass `admin`.

I see 3 errors.
```
Error: Failed to log in as admin with password password
    login https://playground.wordpress.net/client/index.js:742
    o https://playground.wordpress.net/client/index.js:9386
    run https://playground.wordpress.net/client/index.js:9313
    runBlueprintSteps https://playground.wordpress.net/client/index.js:9421
    startPlaygroundWeb https://playground.wordpress.net/client/index.js:9903
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:48
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:61
[index.js:9316:27](https://playground.wordpress.net/client/index.js)
Uncaught (in promise) Error: Error when executing the blueprint step #2 ({"step":"login"}) : Failed to log in as admin with password password
    run https://playground.wordpress.net/client/index.js:9316
    runBlueprintSteps https://playground.wordpress.net/client/index.js:9421
    startPlaygroundWeb https://playground.wordpress.net/client/index.js:9903
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:48
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:61
Caused by: Error: Failed to log in as admin with password password
    login https://playground.wordpress.net/client/index.js:742
    o https://playground.wordpress.net/client/index.js:9386
    run https://playground.wordpress.net/client/index.js:9313
    runBlueprintSteps https://playground.wordpress.net/client/index.js:9421
    startPlaygroundWeb https://playground.wordpress.net/client/index.js:9903
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:48
    async* https://test.local/wp-content/plugins/playground/assets/js/playground.js?ver=6.4.3:61
[index.js:9316:37](https://playground.wordpress.net/client/index.js)
```

**Comment by bgrgicak** [comment]
@janw-me we just [released a new version of the Playground plugin](https://github.com/WordPress/playground-tools/releases/tag/v0.0.2) that should fix your issues. Would you be able to update your plugin with the new version and let us know if everything works now?
