### ISSUE TITLE
wp-now: Add "quickstart" section to readme.md

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/playground-tools#194]
I'm looking at  [wp-now's readme](https://github.com/WordPress/playground-tools/blob/trunk/packages/wp-now/README.md) via https://www.npmjs.com/package/@wp-now/wp-now wondering if there's any value for having a Quickstart section that is somewhat self-explanatory since it's supposed to be a simple application (and it is) and I shouldn't have to read much to get started. Thoughts? 

Additionally, we should probably cd into the theme folder before installing wp-now in the GIF. It isn't clear where the folder came from. It kind of feels like it was installed via the `npm`. I wonder if the GIF should just be the npx call?... IDK Soft opinion.

Something like:

<hr>

# Quickstart

## Environment from a theme
```bash
cd my-theme-directory
npx @wp-now/wp-now start 
```

## Environment from a plugin
```bash
cd my-plugin-directory
npx @wp-now/wp-now start --wp=5.9 
```

## Environment from my wp-content folder
```bash
cd my-wordpress-folder/wp-content
npx @wp-now/wp-now start  --wp=5.9 --php=7.4 --blueprint=path/to/blueprint-example.json
```

**Comment by adamziel** [comment]
This sounds lovely! CCing @wojtekn and @sejas who created the original GIF

**Comment by sejas** [comment]
@StevenDufresne , @adamziel ,
I added this PR updating the GIF and adding the quickstart section to README
Let me know what you think.

I see the `Usage` section was aiming to be that quickstart, but I think it makes sense to have a short TLDR at the top.
