### ISSUE TITLE
wp-now: Can't upload media files

### ISSUE THREAD

**Issue by fluiddot** [WordPress/playground-tools#202]
## Description

Media files can't be uploaded to sites created with `wp-now`. Uploads fail with the error `Specified file failed upload test.`.

<img width="247" alt="image" src="https://github.com/WordPress/playground-tools/assets/14905380/024a17cc-ba57-4925-955f-62be618152ce">

## How to reproduce it

> [!NOTE]
> I also reproduce this issue when building `wp-now` locally.

1. Run the command `npx wp-now start`
2. Navigate to WP admin of the site.
3. Navigate to Media page.
4. Upload an image file.
5. Observe the upload fails with the error `Specified file failed upload test.`

**Comment by fluiddot** [comment]
Seems this might be related to changes from https://github.com/WordPress/wordpress-playground/pull/1018. We'd need to update the way we pass files on the PHP request ([reference](https://github.com/WordPress/playground-tools/blob/b3a3baf101c197c6da10e720da5a464451cc9e96/packages/wp-now/src/start-server.ts#L90-L103)).

**Comment by sejas** [comment]
@fluiddot , yes! exactly. Good finding. In https://github.com/WordPress/wordpress-playground/pull/1018 Playground core removed the custom `files` property in favor of only multipart form data.
I created a PR that fixes it 🤞 .

**Comment by fluiddot** [comment]
Thank you so much @sejas for working on a fix 🙇 ! I've just tested the PR and works like a charm.
