### ISSUE TITLE
[VS Code Extension] Specified file failed upload test.

### ISSUE THREAD

**Issue by flexseth** [WordPress/playground-tools#206]
When trying to upload images to the media library.
When trying to upload to a post or page it returns `No data supplied.`

[Relevant Trac ticket](https://meta.trac.wordpress.org/ticket/7535)

**Comment by flexseth** [comment]
> Some requests may not succeed. This is likely due to the fact that we have a minimally implemented server translation layer.

This may be a [known limitation](https://github.com/WordPress/playground-tools/tree/trunk/packages/vscode-extension/#readme) of running the Playground in VS Code. If so, it may be helpful to make users aware of the media upload limitation as it's a key feature of using WordPress (no access to filesystem)

It's also possible that I'm not quite yet well aware of how to use Playground! And that media should be handled in another way via Blueprints (and this is more the intended behavior)

It looks like it's necessary to mount files to the filesystem to interact with them? To that degree, using VS Code with Playground would be best implemented with a Blueprint based approach...

**Comment by adamziel** [comment]
[This PR](https://github.com/WordPress/playground-tools/pull/203) might have fixed it. Does it work on the latest extension version (0.1.67)

**Comment by flexseth** [comment]
Fixed!
