### ISSUE TITLE
The theme directory "twentytwentyfour" does not exist.

### ISSUE THREAD

**Issue by flexseth** [WordPress/playground-tools#232]
Error when booting in `wp-content` mode without a theme in the folder.

> The theme directory "twentytwentyfour" does not exist.
> Error: The themes directory is either empty or does not exist. Please check your installation.

## Why is this a problem
A theme is necessary to run any WordPress website. Let's make sure one is available. 

## Suggested fix
If no theme is in the `wp-content/themes` folder, install [Twenty Twenty-Four](https://github.com/WordPress/twentytwentyfour)

Step to install Twenty Twenty-Four (doesn't work but seems like it should)
```JSON
{
	"step": "installTheme",
            "themeZipFile": {
                "resource": "wordpress.org/themes",
                "slug": "twentytwentyfour"
            },
            "options": {
                "activate": true
            }	
}
```
> source: https://wordpress.github.io/wordpress-playground/blueprints-api/steps#InstallThemeStep**

### Error code on attempted theme install - partially redacted
> Starting the server......
directory:........./playground-docs-workflow/wp-content
mode: wp-content
php: 8.0
wp: 6.5.2
WordPress 6.5.2 folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
blueprint steps: 3
Blueprint step completed: unzip
Blueprint step completed: activatePlugin
Error: Could not move /var/www/html/wp-content/ieU!7ZbrcT$JApjm3Z/5Z,wbT@NiKARm7ucg/assets/Twentytwentyfour/twentytwentyfour to /var/www/html/wp-content/themes/twentytwentyfour: There is no such file or directory OR the parent directory does not exist.

## Affects
- VS Code Extension booted in `wp-content` mode
- `wp-now` when booted in `wp-content` mode

## How to re-create the issue
- Clone the https://github.com/adamziel/playground-docs-workflow repo
- Click "Start Server" in VS Code or run `wp-now`
- `npx @wp-now/wp-now start  --wp=6.5.2 --php=8.0 --blueprint=blueprint.json`

## `blueprint.json`
```JSON
{
	"$schema": "https://playground.wordpress.net/blueprint-schema.json",
	"landingPage": "/wp-admin/edit.php?post_type=doc_page",
	"preferredVersions": {
		"wp": "6.4",
		"php": "7.4"
	},
	"features": { "networking": true },	
	"login": true,
	"steps": [
		{
			"step": "unzip",
			"zipFile": {
				"resource": "url",
				"url": "https://github-proxy.com/partial/adamziel/playground-docs-workflow/wp-content"
			},
			"extractToPath": "/wordpress"
		},
		{
			"step": "activatePlugin",
			"pluginPath": "wp-docs-plugin/plugin.php"
		},
		{
			"step": "installTheme",
            "themeZipFile": {
                "resource": "wordpress.org/themes",
                "slug": "twentytwentyfour"
            },
            "options": {
                "activate": true
            }	
		}
	]
}
```

I double checked the syntax on the blueprint with the `{}` and it's correct

**networking** is enabled - but possibly the culprit?

**Comment by flexseth** [comment]
Looks like it may be a URL or "resource type" issue

 
<img width="649" alt="Screenshot 2024-04-12 at 9 56 43 PM" src="https://github.com/WordPress/wordpress-playground/assets/3792502/cdcf3642-0f7c-46b7-a941-4a677ae7244f">
<img width="845" alt="Screenshot 2024-04-12 at 9 55 36 PM" src="https://github.com/WordPress/wordpress-playground/assets/3792502/7cc4c412-6a51-48e5-9e7b-addaa6c2a081">

**Comment by sejas** [comment]
- Closing in favor of https://github.com/WordPress/playground-tools/issues/265
