### ISSUE TITLE
Quiet startup mode

### ISSUE THREAD

**Issue by mhsdef** [WordPress/playground-tools#248]
It looks like `wp-now` always opens a browser unless in a Github codespace (`openInDefaultBrowser`).

Could we get a CLI flag to background `wp-now` after startup and skip opening the browser?

Eg, something like:
```
wp-now --quiet
```

Use case:
Scripted spin up of both wp-now as a backend and a separate verbose frontend such as vite dev server.

**Comment by eliot-akira** [comment]
On a related note: I was looking for a way to silence any console output from `wp-now`. Currently, as far as I can tell, the only way to achieve it is by setting the environment variable `NODE_ENV` to `test` (checked on startup [here](https://github.com/WordPress/playground-tools/blob/1a54e43bd6ef09a33b247468738f46eb1798ca68/packages/wp-now/src/output.ts#L2)). There is a function called `disableOutput()` but it's not exposed as a CLI option.

The new proposed option `--quiet` sounds like it's about logging level, as opposed to `--verbose`. Maybe it could be named something like `--no-open`, to clarify that it prevents automatically opening the browser on start.

**Comment by sejas** [comment]
@mhsdef , @eliot-akira , now you can run `npx @wp-now/wp-now@latest start --skip-browser`

Thanks for suggesting this feature! 🙌
