### ISSUE TITLE
Playground block: A11Y: Remove duplicate main landmarks

### ISSUE THREAD

**Issue by alexstine** [WordPress/playground-tools#292]
Test page: https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/

Every time the Playground block is used, it renders a `<main>` landmark. Really, this landmark should only be used once per page. Can this be replaced by another tag? Maybe just a generic `<div>`? You could also replace this with a `<section aria-label="Playground">` but I think if the Playground block has surrounding headings, it's not a big deal.

**Comment by brandonpayton** [comment]
Thanks for flagging this, @alexstine!

**Comment by alexstine** [comment]
Working well, thanks!
