### ISSUE TITLE
Playground block: A11Y: Add skip links for loaded preview/iFrame

### ISSUE THREAD

**Issue by alexstine** [WordPress/playground-tools#293]
Test page: https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/

After the Playground iFrame is loaded, there is no way for users to easily skip it. Could we append a "Skip passed iFrame" link or similar? Code structure could look something like this.

```
<span class="accessible-text">Beginning of Playground preview</span>
<a href="#">Skip Playground Preview</a>
<span class="accessible-text" tabindex="-1">End of Playground preview</span>
```

Focus could land on that last span with the `tabindex="-1"` set.

This will offer users to easily skip the frame since the content within the frame will also have semantics exposed to screen reader users such as headings and landmarks which could be used to skip content in other situations.

**Comment by brandonpayton** [comment]
A number of these accessibility issues were closed via "fixes X" commit messages, but it would be better if we leave these open until we tag a new release and @alexstine confirms they are indeed fixed. So I've reopened all of them until then.

**Comment by alexstine** [comment]
@brandonpayton I won't know until I have a place to test it.

**Comment by brandonpayton** [comment]
@alexstine the changes haven't been included in a new plugin release yet. Once there is a new release of the [interactive-code-block](https://wordpress.org/plugins/interactive-code-block/) plugin, will that be sufficient for you to test, or does something else need to be updated in WP.org infrastructure in order to test the new release? (I'm not very familiar with how things are set up for WordPress.org or learn.wordpress.org)

**Comment by alexstine** [comment]
@brandonpayton Once the plugin is released, let's ping Adam and see if he can sync the new changes to our test page on Learn.

Thanks.

**Comment by jonathanbossenger** [comment]
Hi folks. 

@brandonpayton, once the new version of the plugin has been released in the WordPress.org plugin directory, I usually ask one of the meta team folks to deploy the changes. This usually requires a full deployment of the entire .org network, so depending on what else needs to get done, this can happen in a day or over a few days.

We have a [testing issue in the Learn.WordPress.org repo](https://github.com/WordPress/Learn/issues/2352) that we're using to test these fixes. Would you be able to ping me there once there's a new version in the plugin directory, and then I'll wrangle getting it deployed to Learn?

**Comment by brandonpayton** [comment]
> once the new version of the plugin has been released in the WordPress.org plugin directory, I usually ask one of the meta team folks to deploy the changes.

@jonathanbossenger Thank you for explaining how updating typically works. 

> We have a https://github.com/WordPress/Learn/issues/2352 that we're using to test these fixes. Would you be able to ping me there once there's a new version in the plugin directory, and then I'll wrangle getting it deployed to Learn?

Sounds great! I'll ping you there once there's a new version.

**Comment by alexstine** [comment]
@brandonpayton Is there any way we can remove these from the new window view? If not, that's okay. These are really only needed for the iFrame version only.

**Comment by brandonpayton** [comment]
> @brandonpayton Is there any way we can remove these from the new window view? If not, that's okay. These are really only needed for the iFrame version only.

@alexstine, it's no problem to remove the skip link. Should the "Beginning of Playground Preview" and "End of Playground Preview" markers remain in place, or should they be removed as well?

**Comment by alexstine** [comment]
@brandonpayton Those can also be removed. Thanks.

**Comment by brandonpayton** [comment]
> @brandonpayton Those can also be removed. Thanks.

👍 Got it. Thanks. Those are removed by #333 which will be included when we tag a new release.

**Comment by adamziel** [comment]
@brandonpayton is this one now resolved?

**Comment by brandonpayton** [comment]
This was [tested by someone with a11y expertise](https://github.com/WordPress/Learn/issues/2352#issuecomment-2332416410) and can now be marked as resolved.
