### ISSUE TITLE
Local Environment: Add some ability to reset a given project

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#30]
`rm -r ~/.wp-now` is a bit of a nuclear option. It would be nice to be able to reset a specific project without deleting everything.

**Done is:**
* There's some ability to reset a given project.

**Comment by danielbachhuber** [comment]
@adamziel What do you think about adding a 'Reset' button to the VS Code Extension too?

**Comment by adamziel** [comment]
In the VS Code I’m not convinced the concept of auto-retaining changes in `~/.wp-now` makes sense.

If I start WordPress server in a plugin directory, I expect a fresh WordPress site - that’s simple to reset and easy to grasp. If the site is persistent then suddenly the tool must answer a bunch of questions like:

* Where does my WP live?
* How do I access wp-content? Can I change it?
* Which files are reusable and which are site-specific?
* What sites do I have?
* Where’s the database?
* How do I reset the site?
* How do I export my site?
* …and a lot more

I’m thinking about keeping it simple. To retain data, I’d just start the WordPress server in a WordPress core directory where I’m in charge of the database and the project state.

The VS code extension has a bit of screen space available and can explain it in a sentence or two.

**Comment by danielbachhuber** [comment]
As I reviewed https://github.com/WordPress/gutenberg/pull/51200, I felt myself wanting `wp-now start` to initialize a fresh environment each time.

Maybe we remove the persistence behavior entirely? This would be something to get user feedback on.

**Comment by dcalhoun** [comment]
I have benefitted from the ability to persist content and settings while developing a site with `wp-now`. That said, I found this issue while seeking a "reset" command to clear out content. 😄 I'd welcome a reset feature. 

I understand removing the persistence behavior entirely would simplify things. However, I do think I would find myself missing it.

**Comment by danielbachhuber** [comment]
Feel free to submit a PR if you'd like! I think something like `wp-now start --reset` would suffice.

**Comment by dcalhoun** [comment]
👋🏻 @danielbachhuber. I opened https://github.com/WordPress/playground-tools/pull/95 for your consideration. 🙇🏻‍♂️
