### ISSUE TITLE
wp-now feature request : run phpunit tests within wp-now

### ISSUE THREAD

**Issue by lgersman** [WordPress/playground-tools#321]
It would be a bummer if wp-now could be used to run PHPUnit testcases. 

Right now I used to use wp-env for running PHPUnit tests in the CI pipeline. But wp-env is huge in terms of required ressources.

If wp-now would be able to run PHPUnit tests right in the browser, all testing (both e2e and PHPUNit) could be done using only the playwright framework. So much leaner than wp-env ...

I could find only a short notice in #28 that PHPUnit is not working. 

What's the concrete problem ?

**Comment by adamziel** [comment]
@lgersman This is a larger Playground issue tracked in https://github.com/WordPress/wordpress-playground/issues/111. I wonder how many PHPUnit tests would actually pass today, I haven't checked for a while. Would you be game for exploring?

**Comment by lgersman** [comment]
Hi @adamziel, 

for whatever reason i did not realized #11 before 😅. 

Will have a look into it. 

Thanks.

**Comment by adamziel** [comment]
Closing as a duplicate
