### ISSUE TITLE
Playground on Learn.WordPress.org

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#322]
Let's solve all the Playground block accessibility issues:

https://github.com/WordPress/playground-tools/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3AAccessibility

Related: https://github.com/WordPress/wporg-developer/issues/520

**Comment by bgrgicak** [comment]
I renamed the issue to match[ the project on the board](https://github.com/orgs/WordPress/projects/180/views/11)

**Comment by adamziel** [comment]
I understand the Playground block is now enabled on learn.wordpress.org so let me close this issue. CC @brandonpayton @jonathanbossenger @westnz
