### ISSUE TITLE
Local Environment: Child theme can't be activated

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#33]
If you run `wp-now --path=/path/to/child-theme`, the theme can't be activated because the parent theme is missing.

The parent theme is missing because it isn't mounted into the filesystem.

**Done is:**
* We're processing the `style.css` file for the parent them.
* If there is a parent theme, we mount the corresponding directory to the filesystem.

**Comment by sejas** [comment]
@katinthehatsite, Do you want to take this one?

**Comment by katinthehatsite** [comment]
let's do this - or at least attempt 😅

**Comment by danielbachhuber** [comment]
@katinthehatsite I'm going to pick this up so you can focus on your upcoming project.

**Comment by danielbachhuber** [comment]
With some more reflection, I actually want to hold off on fixing this for now:
* https://github.com/WordPress/playground-tools/issues/19 might be a more durable fix, because the parent theme can be located in other theme directories.
* It might be nice to automatically install the parent theme from WordPress.org, but I don't know if this is a safe assumption to make.

I'd love to hear more reports from folks who run into this in the wild, and what their scenario is.

**Comment by cpapazoglou** [comment]
> * It might be nice to automatically install the parent theme from WordPress.org, but I don't know if this is a safe assumption to make.

If it doesn't exist locally and if it's a .org theme, yes, it would be nice!

**Comment by dmsnell** [comment]
Noting here that WordPress also fails if the parent theme is missing. If we can mirror WordPress behavior that seems sufficient. If WordPress can auto-install then that seems reasonable, but for many themes we know this is impossible because they don't exist in the registry.

For those cases it seems sufficient to scope-limit this tool to _not_ solve problems WordPress itself doesn't solve.

**Comment by danielbachhuber** [comment]
I'm also not sure if we can know definitively that a given theme is a WordPress.org theme.

**Comment by cpapazoglou** [comment]
> I'm also not sure if we can know definitively that a given theme is a WordPress.org theme.

3pd themes _usually_ don't have a slug used in .org. For example

`https://api.wordpress.org/themes/info/1.1/?action=theme_information&request%5Bslug%5D=astra` returns data for `astra` theme.

**Comment by wojtekn** [comment]
> For those cases it seems sufficient to scope-limit this tool to not solve problems WordPress itself doesn't solve.

I agree with @dmsnell , local environment tool shouldn't solve WordPress problems that way.

Activating the parent theme would be enough, assuming we use 'wp-content' mode with both themes available or we have support for paths mapping.

**Comment by danielbachhuber** [comment]
This came up again with https://github.com/WordPress/playground-tools/issues/39

For now, let's mount the parent theme directory too if it sits alongside the child theme. More complex configurations can be handled with https://github.com/WordPress/playground-tools/issues/19
