### ISSUE TITLE
Playground block: Hide open-in-new-tab arrow icon from screen readers

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/playground-tools#330]
From @alexstine [here](https://github.com/WordPress/Learn/issues/2352#issuecomment-2240790504):

> Could you please hide the arrow icon to screen readers for the Open in New Tab button? Looks like you are using the :after selector to add it so you could either add it in a span with aria-hidden or simply add aria-label="Open in New Tab" to the button.

**Comment by adamziel** [comment]
@brandonpayton is this one now resolved, since #336 is merged?

**Comment by brandonpayton** [comment]
This was [tested by someone with a11y expertise](https://github.com/WordPress/Learn/issues/2352#issuecomment-2332416410) and can now be marked as resolved.
