### ISSUE TITLE
Playground block: Add ability to switch between side-by-side and top-bottom layouts at runtime

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/playground-tools#335]
Requested [here](https://github.com/WordPress/Learn/issues/2664#issuecomment-2225042344) by @jasmussen as "Buttons for changing layout to stacked or side by side."

**Comment by adamziel** [comment]
@brandonpayton is this something you think we should prioritize in the short term? Or let's punt it?

**Comment by brandonpayton** [comment]
@adamziel Since we haven't heard any more from the Learn folks about this, I think we can punt for now.
