### ISSUE TITLE
运行器运行蓝图产生游乐场

### ISSUE THREAD

**Issue by 13409820605** [WordPress/playground-tools#347]
设备手机闪退转回
![Screenshot_20240817_123222](https://github.com/user-attachments/assets/7a6231be-1bcf-41a8-996c-c8dc771fefc5)
![Screenshot_20240817_113351](https://github.com/user-attachments/assets/d5f80bd8-4865-4848-856d-a94e078ca513)

**Comment by brandonpayton** [comment]
@13409820605 Hi there, thank you for reporting this. Would you be willing to share the URL of the page that led to the crash?

**Comment by adamziel** [comment]
I'll close since there was no reply from the author. Let's reopen whenever more information comes.
