### ISSUE TITLE
Firefox dev build service worker crash

### ISSUE THREAD

**Issue by ajlende** [WordPress/playground-tools#356]
## Description

I didn't see any issues with the service worker script, but it crashes on registration.

## Error

```
TypeError: ServiceWorker script at http://127.0.0.1:5400/service-worker.ts?type=module&worker_file for scope http://127.0.0.1:5400/ threw an exception during script evaluation.
```

## Steps to reproduce

1. Regular development workflow (`npm install && npm run dev`)
2. Open the site
3. See the generic error page

## Versions

Playground: f5f9d057a34f3870788257f815bd1cfb21d81326
Browser: Firefox Developer Edition 131.0b4 (aarch64), Firefox 130.0.1 (64-bit)

**Comment by brandonpayton** [comment]
Hi @ajlende, thank you for reporting this. It's an unfortunate issue, and if we want to see Playground dev server work with Firefox in the near term, it will likely require us changing the dev server to not use an ES module Service Worker. Ultimately, we'd love to see Firefox support ES module Service Workers though.

It looks like we already have an issue for this, so let's close this issue as a duplicate.
https://github.com/WordPress/wordpress-playground/issues/845
