### ISSUE TITLE
Error: Invalid blueprint: must have required property 'pluginZipFile'

### ISSUE THREAD

**Issue by evrpress** [WordPress/playground-tools#361]
I try to run a local blueprint with this command:

```shell
npx @wp-now/wp-now start --blueprint=blueprint.json --reset
```

and get the error
```
Error: Invalid blueprint: must have required property 'pluginZipFile' at /steps/1
```

Here's my blueprint:

```json
{
    "siteOptions": {
        "blogname": "My first Blueprint"
    },
    "steps": [
        {
            "step": "installTheme",
            "themeData": {
                "resource": "wordpress.org/themes",
                "slug": "adventurer"
            }
        },
        {
            "step": "installPlugin",
            "pluginData": {
                "resource": "wordpress.org/plugins",
                "slug": "hello-dolly"
            }
        }
    ]
}
````
[Playground link](https://playground.wordpress.net/#eyJzaXRlT3B0aW9ucyI6eyJibG9nbmFtZSI6Ik15IGZpcnN0IEJsdWVwcmludCJ9LCJzdGVwcyI6W3sic3RlcCI6Imluc3RhbGxUaGVtZSIsInRoZW1lWmlwRmlsZSI6eyJyZXNvdXJjZSI6IndvcmRwcmVzcy5vcmcvdGhlbWVzIiwic2x1ZyI6ImFkdmVudHVyZXIifX0seyJzdGVwIjoiaW5zdGFsbFBsdWdpbiIsInBsdWdpblppcEZpbGUiOnsicmVzb3VyY2UiOiJ3b3JkcHJlc3Mub3JnL3BsdWdpbnMiLCJzbHVnIjoiaGVsbG8tZG9sbHkifX1dfQ=)

Switching the `pluginData` property to the deprecated `pluginZipFile` will work, but it breaks my blueprint on the playground.

**Comment by zaerl** [comment]
Hi @evrpress, thanks for this. I can confirm. I checked, and I can see `wp-now` is loading [wp-playground/blueprints 1.0.2](https://github.com/WordPress/playground-tools/blob/trunk/package.json#L43). Upgrading to `1.0.14` will probably automatically fix this. Now the required elements are `["pluginData", "step"]`.

cc. @adamziel

**Comment by adamziel** [comment]
@evrpress you may have more luck with `@wp-playground/cli`. `@wp-now` is not actively maintained and upgrading the Playground libraries is a real challenge. I'd love to merge it into `@wp-playground/cli` and only maintain a single too. To do that, we'd need to port the context detection logic (as in – are we in a plugin directory? Or a theme directory? Or wp-content? etc.) into `@wp-playground/cli`

**Comment by adamziel** [comment]
I've created a new issue to track that here: https://github.com/WordPress/wordpress-playground/issues/2100
