### ISSUE TITLE
IPV6 on WSL2 - can't connect

### ISSUE THREAD

**Issue by khromov** [WordPress/playground-tools#40]
I am running wp-now on Windows 11 in WSL2. It starts and says:

```
Server running at http://127.0.0.1:8881/
```

However, if I go to the URL it does not work properly. If I debug it from inside the WSL2 terminal, it seems that it's only listening on the ipv6 interface:

```
/home/k# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:40069         0.0.0.0:*               LISTEN      1791/node
tcp6       0      0 :::8881                 :::*                    LISTEN      1791/node
```

It should say `127.0.0.1:8881`, not `:::8881`.

So 127.0.0.1 does not work. http://localhost:8881/ works because it does correctly resolve to the ipv6 address, but all the resources are linked incorrectly from 127.0.01 because the `siteurl` is set to that.

**Comment by t-hamano** [comment]
Hi @khromov,

I experienced the same problem. I believe that problem will be solved with WordPress/wordpress-playground#455.

**Comment by t-hamano** [comment]
The URL that wp-now listens on has changed to localhost:8881 due to WordPress/wordpress-playground#455 being merged. I believe a global install of the latest wp-now will resolve this issue.

**Comment by danielbachhuber** [comment]
@khromov This should be fixed now! Feel free to re-open the issue if it isn't
