### ISSUE TITLE
Support pretty permalinks

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#53]
The `index.php` is ugly:

<img width="959" alt="image" src="https://github.com/WordPress/playground-tools/assets/36432/28b50877-1307-45d3-b17a-1b469573edbb">

**Done is:**
* Both `wp-now` and the VS Code Extension support pretty permalinks without the `index.php`.

**Comment by adamziel** [comment]
How does WordPress decide to put `index.php` in there?

**Comment by danielbachhuber** [comment]
> How does WordPress decide to put `index.php` in there?

Two parts:

* https://github.com/WordPress/wordpress-develop/blob/aaf778c6a17954fa8a7e9be18009d39e7e606d39/src/wp-admin/options-permalink.php#L79-L81
* https://github.com/WordPress/wordpress-develop/blob/aaf778c6a17954fa8a7e9be18009d39e7e606d39/src/wp-admin/includes/misc.php#L34-L56
