### ISSUE TITLE
[wp-now] `/wp-admin` should redirect to `/wp-admin/`

### ISSUE THREAD

**Issue by danburzo** [WordPress/playground-tools#65]
Hi everyone, I've just discovered `wp-now` and I'm super excited about having a self-contained local WordPress development environment, so congrats on the initiative!

I noticed that `http://localhost:8881/wp-admin` does not redirect to `http://localhost:8881/wp-admin/` (with a trailing slash), which causes all links in the left sidebar to exclude `wp-admin`, e.g. `http://localhost:8881/plugins.php` instead of `http://localhost:8881/wp-admin/plugins.php`.

**Comment by danielbachhuber** [comment]
Thanks for the report, @danburzo !

This was fixed with https://github.com/WordPress/playground-tools/pull/60. We'll tag a new release for it in the next day or so.

**Comment by danburzo** [comment]
Ah, that's great to hear, I missed that.
