### ISSUE TITLE
wp-now requires nvm to run

### ISSUE THREAD

**Issue by dmsnell** [WordPress/playground-tools#7]
After building `wp-now` I attempted to run it, but it failed because a dependency on `nvm` has apparently bled into the project, and since I don't have `nvm` and don't want `nvm` the `bin/wp-now` command fails, which should not happen.

A fix is when running a "binary" doesn't depend on a third-party development version manager.

**Comment by danielbachhuber** [comment]
@dmsnell Do you mean this binary? https://github.com/WordPress/wordpress-playground/blob/trunk/bin/wp-now

**Comment by adamziel** [comment]
Yes

**Comment by wojtekn** [comment]
We have `nvm` listed as a requirement for the project in [CONTRIBUTING](https://github.com/WordPress/wordpress-playground/blob/trunk/packages/wp-now/CONTRIBUTING.md).md docs, so technically, the project depends on it. However, it would be better if running such an executable file wouldn't change the developer's environment.

@danielbachhuber, as we recommend running `nvm use` as part of development setup steps, do we need those in the `bin/wp-now` file?

```
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;
nvm use
```

If we remove them, the linked wp-now would be just responsible for running `nx preview wp-now` from the `wordpress-playground`, pretending it runs from the project directory, and wouldn't modify the developer's environment in any way. 

As far as I see, we would still be able to link and run `wp-now` globally, and the command would work for developers who don't want to use nvm.
