### ISSUE TITLE
wp-now: Support for running a Blueprint on start

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#80]
[Blueprints](https://wordpress.github.io/wordpress-playground/docs/blueprints-api/index) are an abstraction for configuring the WordPress install. Let's make it possible to run a Blueprint file when starting:

```bash
wp-now start --blueprint=blueprint.json
```

**Done is:**
* `wp-now start` supports a `--blueprint=<file>` argument. We should support arbitrary file names, as long as they validate against the JSON Schema.
* When a Blueprint is provided, `wp-now start` validates it against the JSON Schema first and throws an error if it doesn't validate.
* If a valid Blueprint is provided, it's applied when `wp-now start` runs.
* We have some amount of corresponding test coverage.
* Our `README.md` is updated to document how Blueprints work, including examples for https://github.com/WordPress/playground-tools/pull/78 and https://github.com/WordPress/playground-tools/issues/17

**Comment by danielbachhuber** [comment]
> examples for https://github.com/WordPress/playground-tools/pull/78

For this particular scenario, what would be optimal is the ability to add the following to `wp-config.php`:

```php
define( 'WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] );
define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] );
```

However, wp-now is currently defining these on its own, so they can't be defined again. We should figure out a more elegant solution here.

**Comment by adamziel** [comment]
JSON schema validation would be a very useful core feature. Btw, the Schema file is autogenerated in core from Typescript types.


As for the site url, Blueprints have a step called defineWpConfigConst that can be called multiple times with the same consts to override the previously defined values.

**Comment by adamziel** [comment]
Also there’s a DefineSiteUrlStep step

**Comment by sejas** [comment]
> > examples for #78
> 
> For this particular scenario, what would be optimal is the ability to add the following to `wp-config.php`:
> 
> ```
> define( 'WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] );
> define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] );
> ```
> 
> However, wp-now is currently defining these on its own, so they can't be defined again. We should figure out a more elegant solution here.

This approach worked well for localhost, but it failed with http/https protocols when proxying with ngrok.

```
	const configPath = '/wp-now-vfs/wp-config.php'
	php.mkdir(path.dirname(configPath));
	php.setPhpIniEntry('auto_prepend_file', configPath);
	php.writeFile(
		configPath,
		`<?php
			define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] );
			define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] );
			`
	);
```
