### ISSUE TITLE
wp-now: Include minimum node.js and npm requirements

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/playground-tools#83]
After installing wp-now, I attempted to run it in "WordPress" mode by simply calling `wp-now start` inside a local WordPress directory. I was met with "ReferenceError: Event is undefined errors", which was due to running node.js version 14. I had to bump my version up to at latest LTS (version 18.20 at the time of this writing).  

Therefore it might be a good idea to include a "minimum node.js and npm" requirements section in the wp-now readme.md. 

FWIW this is probably because Gutenberg development used to require v 14 of node.js, but I think this has recently been updated, and I'm still on the old version.

**Comment by danielbachhuber** [comment]
Thanks for the report, @jonathanbossenger !

> I was met with "ReferenceError: Event is undefined errors", which was due to running node.js version 14.

Out of curiosity, did you see this warning?

https://github.com/WordPress/playground-tools/blob/02f25d4ac40d40c10111869a72b470342e80d962/packages/wp-now/src/main.ts#L7-L11

> Therefore it might be a good idea to include a "minimum node.js and npm" requirements section in the wp-now readme.md.

Sounds great! Feel free to submit a pull request if you'd like.

**Comment by jonathanbossenger** [comment]
> Out of curiosity, did you see this warning?

Interestingly, no I did not, but it looks like this was merged on the same day as I had the error, so it's possible I did this before the update.

I'll `nvm use 14` to test. If that notification exists, then perhaps the documentation update is not needed. 🤔 

That being said, as a documentation nerd, I'm never going to not want to document requirements. 😁 Will work on the PR.

If I could ask you to assign this ticket to me? Thanks

**Comment by danielbachhuber** [comment]
@ndiego ran into the same error and I was able to reproduce, so I'll get that fixed up when I have a moment. I'll also document the minimum node version when I do.

Related https://github.com/WordPress/playground-tools/issues/87

**Comment by juanmaguitar** [comment]
> I'll also document the minimum node version when I do.

@danielbachhuber At https://github.com/WordPress/gutenberg/pull/52462 I'm working on a Quick Start Guide for the Interactivity API where `wp-now` is recommended.
It would be great if I could include a link to the minimum requirements for `wp-now` along with this recommendation.

**Comment by danielbachhuber** [comment]
We documented the minimum and recommended Node versions with https://github.com/WordPress/playground-tools/pull/90

We also looked into showing the warning message for Node 14. For a variety of technical complications, we're going to leave things as-is. Gutenberg should switch to Node 18 shortly, which should improves the rocky user experience for Gutenberg contributors: https://github.com/WordPress/gutenberg/pull/52363
