### ISSUE TITLE
wp-now: Restore node 18 support

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#87]
Minimum supported version was bumped to node 20 in https://github.com/WordPress/playground-tools/pull/82#discussion_r1247217708 but we should keep node 18 support for now.

**Done is:**
* Minimum supported version is 18.
* For any node 20 feature, we throw a warning (or error) if the current version is node 18.

**Comment by danielbachhuber** [comment]
@sejas Just wanted to let you know that @dmsnell worked through this and put together https://github.com/WordPress/playground-tools/pull/90.

As it turns out, `wp-now start` still works fine on Node 18. `wp-now start --blueprint=blueprint.json` will crash, but that's documented now in the README. I think this is a fine place for now.

**Comment by sejas** [comment]
@danielbachhuber , @dmsnell, thank you for the change.
- I created this PR https://github.com/WordPress/playground-tools/pull/91 to be consistent with the rest of node version changes.

**Comment by dmsnell** [comment]
Thanks @sejas!

**Comment by amplify11dev** [comment]
> @sejas Just wanted to let you know that @dmsnell worked through this and put together #90.
> 
> As it turns out, `wp-now start` still works fine on Node 18. `wp-now start --blueprint=blueprint.json` will crash, but that's documented now in the README. I think this is a fine place for now.

Where in the README does it call out it will crash in 18? I could be looking at the wrong repo/readme but I ran into this exact issue and didn't see it documented anywhere.

**Comment by danielbachhuber** [comment]
@amplify11dev It's mentioned in "Getting Started":

<img width="1087" alt="CleanShot 2023-08-28 at 03 58 19@2x" src="https://github.com/WordPress/playground-tools/assets/36432/2543a7ad-7a72-452f-ba7e-c77fd5e9194b">

We could probably include a mention in the argument documentation too. Want to submit a PR for that?
