### ISSUE TITLE
WordPress Playground Block

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/playground-tools#94]
While working on [Test Your Site With WordPress 6.3](https://developer.wordpress.com/2023/08/01/test-your-site-with-wordpress-6-3/), I thought it would be cool to embed a WordPress Playground demo for each feature I mentioned ("new Command Palette, a revision system for the Style Book, and simplified menu management").

In order to do this, I think I'd need a WordPress Playground block where I could build a Blueprint to set up the demo I wanted to showcase. I'm not sure if Blueprints support opening specific UI elements on the block editor, so we might need to sort that out too (e.g. Command Palette should load with the command palette already opened, etc.).

**Comment by bph** [comment]
This seems to be in the works now :-) 

- https://github.com/WordPress/playground-tools/pull/126

**Comment by adamziel** [comment]
This is now shipped :tada:

https://wordpress.org/plugins/interactive-code-block/

@jonathanbossenger is looking into deploying it on learn.wp.org.

@bph @annezazu what would it take to ship it on make.wp.org and developer news?

**Comment by adamziel** [comment]
I’ll go ahead and close this issue. Let’s track any follow-ups separately.
